#!/usr/bin/env bash

# <doc>
#
# _manage is a model for setting up shell programs that use
# subcommands.
#
# For more details on how to define your own commands look
# online at https://github.com/eitherlands/_manage
#
# </doc>

#
# Configuration Options

[ -z "$MANAGEDIRECTORY" ]        && MANAGEDIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
[ -z "$MANAGEINIT" ]             && MANAGEINIT="$( basename "${BASH_SOURCE[0]}" )"
[ -z "$MANAGEPATH" ]             && MANAGEPATH="${MANAGEDIRECTORY}"/"${MANAGEINIT}"
[ -z "$MANAGESCRIPTSDIRECTORY" ] && MANAGESCRIPTSDIRECTORY="script"

# export MANAGEDIRECTORY
# export MANAGEINIT
# export MANAGEPATH
#
_exit () {
    local arg=${1:-0}
    # [ -n "$1" ] && numarg="$1"
    local OPWD="${MANAGEOPWD}"
    _cleanup
    [ -d "${OPWD}" ] && cd "${OPWD}" || exit "${arg}"
    exit "${arg}"
}

_cleanup () {
    unset MANAGEINIT
    unset MANAGEPATH
    unset MANAGETOPIC
    unset MANAGEIMPORTS
    unset MANAGEVERBOSE
    unset MANAGEDIRECTORY
    unset MANAGESCRIPTSDIRECTORY
    unset MANAGE_LOADED
    unset MANAGESELFDIRECTORY
    unset MANAGESELFINIT
    unset MANAGEOPWD
}

_import()
{
    local path
    local requirements="$1"
    path="$(cd "${MANAGEDIRECTORY}"/common || _exit ; pwd)"
    local OPWD=$PWD ; cd "${path}" || _exit
    for file in "${path}"/*
    do
        if [   -f "${file}" ] &&
           [   -r "${file}" ] &&
           [ ! -L "${file}" ] &&
           [[ "$(basename "${file}")" =~ ^[-a-zA-Z]*$ ]]
        then
            for requirement in ${requirements[*]}
            do
                if [[ "${requirement}" == "$(basename "${file}")" ]]
                then
                    source "${file}"
                fi
            done
        fi
    done
    cd "${OPWD}" || _exit
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]
then
    _import "${MANAGEIMPORTS}"
else
    _import "manage"
    _harvest "${MANAGEDIRECTORY%%/}"/"${MANAGESCRIPTSDIRECTORY%%/}"

    _enableStrictMode
    _mCatchExceptions

    unset options
    unset OPTIND
    while getopts ":h:?v" options "$@"; do
        _flags "$options"
    done && shift $((OPTIND - 1))
    unset OPTIND
    unset options

    [ "$1" = "--" ] && shift
    _run "$@"
fi
