#!/usr/bin/env bash

# <doc>
#
# _manage is a model for setting up shell programs that use
# subcommands.
#
# For more details on how to define your own commands look
# online at https://github.com/eitherlands/_manage
#
# </doc>

#
# Configuration Options

[ -z "$MANAGEDIRECTORY" ]        && MANAGEDIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
[ -z "$MANAGEINIT" ]             && MANAGEINIT="$( basename "${BASH_SOURCE[0]}" )"
[ -z "$MANAGEPATH" ]             && MANAGEPATH="${MANAGEDIRECTORY}"/"${MANAGEINIT}"
[ -z "$MANAGESCRIPTSDIRECTORY" ] && MANAGESCRIPTSDIRECTORY="script"

export MANAGEDIRECTORY
export MANAGEINIT
export MANAGEPATH

_import()
{
    local path
    local requirements="$1"
    path="$(cd "${MANAGEDIRECTORY}"/common || exit ; pwd)"
    local OPWD=$PWD ; cd "${path}" || exit
    for file in "${path}"/*
    do
        if [   -f "${file}" ] &&
           [   -r "${file}" ] &&
           [ ! -L "${file}" ] &&
           [[ "$(basename "${file}")" =~ ^[-a-zA-Z]*$ ]]
        then
            for requirement in ${requirements[*]}
            do
                if [[ "${requirement}" == "$(basename "${file}")" ]]
                then
                    source "${file}"
                fi
            done
        fi
    done
    cd "${OPWD}" || exit
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]
then
    _import "${MANAGEIMPORTS}"
else
    _requirements=("manage")
    _import "${_requirements[*]}"
    _harvest "${MANAGEDIRECTORY%%/}"/"${MANAGESCRIPTSDIRECTORY%%/}"

    _enableStrictMode
    _catchExceptions

    unset options
    unset OPTIND
    while getopts ":h:?v" options "$@"; do
        _flags "$options"
    done && shift $((OPTIND - 1))
    unset OPTIND
    unset options

    [ "$1" = "--" ] && shift
    _run "$@"
fi
