#!/usr/bin/env bash
# <doc>
#
# _manage is a model for setting up shell programs that use
# subcommands.
#
# For more details on how to define your own commands look
# online at https://github.com/eitherlands/_manage
#
# </doc>

scope="$( [ -d "${BASH_SOURCE[0]%/*}" ] &&
          cd "${BASH_SOURCE[0]%/*}" ;
          source multiplexer )"

"${scope}" "$( cd "$( dirname "${BASH_SOURCE[0]}" )" &&
            pwd )/$( basename "${BASH_SOURCE[0]}")" \
            "$(dirname "${scope}")" \
            "script" \
            "$@"

unset scope
