#!/bin/sh
set -e
#
# This script is meant for quick & easy install via:
#   'curl -sSL https://manage.eitherlands.com/get/ | sh'
# or:
#   'wget -qO- https://manage.eitherlands.com/get/ | sh'
#

url='https://github.com/eitherlands/manage/raw/releases/'

exists() {
    command -v "$@" > /dev/null 2>&1
}

install() {
    if exists manage; then
        cat >&2 <<-'EOF'
	    Warning: the "manage" command appears to already exist on this system.

	    If you already have manage installed, this script can cause trouble, which is
	    why we're displaying this warning and provide the opportunity to cancel the
	    installation.

	    If you installed the current manage package using this script and are using it
	    again to update manage, you can safely ignore this message.

	    You may press Ctrl+C now to abort this script.
	EOF
        ( set -x; sleep 20 )
    fi
}

# wrapped up in a function so that we have some protection against only getting
# half the file during "curl | sh"
install
