#!/usr/bin/env bash
# @import github.com/escapace/manage-examples/spark/spark
# @import github.com/escapace/manage-examples/spark/spark?version=v1.0.0?verify=false

main ()
{
    verbose true
    strict true
}
