#!/usr/bin/env bash
# @import array/join
# @import string/lower
# @import lang/required
# shellcheck disable=SC2034

capitalize ()
{
    #
    # Converts the first character of string to upper case and the remaining to lower case.
    #
    required "$1" || return 1

    local arguments=("$@")
    local string
    string="$(lower "$(join arguments ' ')")"
    echo "${string^}"
}

