#!/usr/bin/env bash
# @import lang/required
# @import string/truncate
# @dependency bc

createPadding ()
{
    required "$1" || return 1

    local length="${1}"
    local chars=${2:-" "}
    local charsLength="${#chars}"
    local maxLength
    local padding

    padding="$(
        maxLength="$(echo "(${length})/${charsLength}" | bc)"

        while [ "${maxLength}" -ge 0 ]
        do
            echo -n "${chars}"
            maxLength=$(( maxLength - 1 ))
        done
    )"

    truncate "${padding}" "${length}"
}
