#!/usr/bin/env bash
# @import string/lower
# @import string/squeeze
# @dependency sed

detox()
{
    #
    # Make text from stdin slightly less insane.
    #

    sed 's/[^A-Za-z0-9 ]/ /g' |
    squeeze | sed 's/ /_/g' | lower
}
