#!/usr/bin/env bash
# @import lang/required

endsWith () {
    required "$1" "$2" || return 1

    local string="$1"
    local target="$2"
    local targetLength="${#target}"
    local suffix="${string:(-${targetLength})}"

    if [[ "${suffix}" = "${target}" ]]
    then
        return 0
    else
        return 1
    fi
}
