#!/usr/bin/env bash
# @dependency sed

joinLines()
{
    #
    # Joins lines from stdin into a string.
    #
    # DELIMITER defaults to ", ".
    #
    # Usage: joinLines [DELIMITER]
    #
    # Usage examples:
    #     echo -e "foo\nbar\nbaz" | joinLines      #==> foo, bar, baz
    #     echo -e "foo\nbar\nbaz" | joinLines "|"  #==> foo|bar|baz
    #

    local delim=${1:-, }

    while read -r; do
        echo -ne "${REPLY}${delim}"
    done | sed "s/$delim$//"
    echo
}
