#!/usr/bin/env bash
# @import string/trim

splitString ()
{
    #
    # Split text from stdin into a list.
    #
    # DELIMITER defaults to ",".
    #
    # Usage: split [DELIMITER]
    #
    # Usage examples:
    #     echo "foo, bar, baz" | split      #==> foo\nbar\nbaz
    #     echo "foo|bar|baz"   | split "|"  #==> foo\nbar\nbaz
    #

    local defaultDelimter=$','
    local delimiter=${1:-${defaultDelimter}}
    local str

    while read -r; do
        OIFS=$IFS; IFS=$delimiter
        for str in $REPLY; do
            IFS=$OIFS
            trim "${str}"
        done
    done
}
