#!/usr/bin/env bash
# @import lang/required
# @import string/trim
# shellcheck disable=SC2001

squeeze ()
{
    #
    # Removes leading/trailing whitespace and condenses all other consecutive
    # whitespace into a single space.

    required "$1" || return 1

    local result
    local char=${2:-[[:space:]]}

    result="$(echo "${1}"| sed "s%\(${char//%/\\%}\)\+%\1%g")"
    trim "${result}" "${char}"
}

