#!/usr/bin/env bash
# @import array/join
# @import lang/required
# @import string/trimLines
# shellcheck disable=SC2034

squeezeLines()
{
    #
    # Removes all leading/trailing blank lines and condenses all other
    # consecutive blank lines into a single blank line.
    #

    required "$1" || return 1

    local arguments=("$@")

    trimLines "$(join arguments '\n')" | sed '/^[[:space:]]\+$/s/.*//g' | cat -s
}
