#!/usr/bin/env bash
# @import lang/required

startsWith () {
    required "$1" "$2" || return 1

    local string="$1"
    local target="$2"
    local targetLength="${#target}"
    local prefix="${string:0:${targetLength}}"

    if [[ "${prefix}" = "${target}" ]]
    then
        return 0
    else
        return 1
    fi
}
