#!/usr/bin/env bash
# @dependency sed
# @import lang/required
# shellcheck disable=SC2001

trimStart()
{
    #
    # Removes all leading whitespace (from the left).
    #
    required "$1" || return 1

    local char=${2:-[:space:]}
    echo "${1}" | sed "s%^[${char//%/\\%}]*%%"
}
