#!/usr/bin/env bash
# @import string/trimEnd
# @import string/trimStart
# @import lang/required

trim()
{
    #
    # Removes all leading/trailing whitespace
    #
    # Usage examples:
    #     echo "  foo  bar baz " | trim  #==> "foo  bar baz"
    #
    required "$1" || return 1

    local char=${2:-[:space:]}

    trimStart "$(trimEnd "$1" "${char}")" "${char}"
}

