#!/usr/bin/env bash
# @import array/join
# @import lang/required
# @import string/trim
# @dependency sed
# shellcheck disable=SC2034

trimLines()
{
    #
    # Removes all leading/trailing blank lines.
    #

    required "$1" || return 1

    local line
    local arguments=("$@")

    (
        while read -r line
        do
            if [ -n "${line}" ]
            then
                trim "${line}"
            else
                echo "${line}"
            fi
        done < <(join arguments '\n')
    ) | sed ':a;$!{N;ba;};s/^[[:space:]]*\n//;s/\n[[:space:]]*$//'
}
