#!/usr/bin/env bash
# @import lang/required
# shellcheck disable=SC2001

trimEnd()
{
    #
    # Removes all trailing whitespace (from the right).
    #
    required "$1" || return 1

    local char=${2:-[:space:]}
    echo "${1}" | sed "s%[${char//%/\\%}]*$%%"
}
