#!/usr/bin/env bash
# @dependency tr
# @import array/join
# @import lang/required
# shellcheck disable=SC2034

upper ()
{
    #
    # Convert string to lowercase.
    #
    required "$1" || return 1

    local arguments=("$@")

    join arguments ' ' | tr '[:lower:]' '[:upper:]'
}
