#!/usr/bin/env bash
# @dependency fold
# @import lang/required
# @import string/trimLines

wrap ()
{
    required "$1" || return 1

    local width=${2:-80}

    trimLines "$(echo "${1}" | fold -c -s -w "${width}")"
}
