#!/usr/bin/env bash
# @import string/commonPrefix
# @dependency rev

#shellcheck disable=SC2120
#shellcheck disable=SC2119

commonSuffix()
{
    #
    # Gets the common suffix of the strings passed on stdin.
    #
    # Usage examples:
    #     echo -e "foobar\nbabar" | commonSuffix  #==> bar
    #     echo -e "broom\ngroom"  | commonSuffix  #==> room
    #

    if (( $# > 0 )); then
        local str
        for str in "$@"; do
            echo "$str"
        done | commonSuffix
        return
    fi

    rev | commonPrefix | rev
}
