#!/usr/bin/env bash

#shellcheck disable=SC2120
commonPrefix()
{
    #
    # Gets the common prefix of the strings passed on stdin.
    #
    # Usage examples:
    #     echo -e "spam\nspace"   | commonPrefix  #==> spa
    #     echo -e "foo\nbar\nbaz" | commonPrefix  #==>
    #

    local i compare prefix

    if (( $# > 0 )); then
        local str
        #shellcheck disable=SC2119
        for str in "$@"; do
            echo "$str"
        done | commonPrefix
        return
    fi

    while read -r; do
        [[ $prefix ]] || prefix=$REPLY
        i=0
        unset compare
        while true; do
            [[ ${REPLY:$i:1} || ${prefix:$i:1} ]] || break
            [[ ${REPLY:$i:1} != ${prefix:$i:1} ]] && break
            compare+=${REPLY:$((i++)):1}
        done
        prefix=$compare
        echo "$prefix"
    done | tail -n1
}
