#!/usr/bin/env bash

indent() {
    local __len=4
    local __int='^[0-9]+$'
    if test "$1"; then
        if [[ $1 =~ $__int ]] ; then
            __len=$1
        fi
    fi
    while [ $__len -gt 0 ]; do
        echo -n " "
        __len=$(( $__len - 1 ))
    done
}
