#!/usr/bin/env bash
# @import string/trim
# @dependency sed

sortList()
{
    #
    # Sorts a list from stdin.
    #
    # Usage: sortList [-ur] [DELIMITER]
    #
    # Usage examples:
    #     echo "c b a"     | sortList       #==> a b c
    #     echo "c, b, a"   | sortList ", "  #==> a, b, c
    #     echo "c b b b a" | sortList -u    #==> a b c
    #     echo "c b a"     | sortList -r    #==> c b a
    #

    local r u

    unset OPTIND
    while getopts ":ur" option; do
        case $option in
            u) u=-u ;;
            r) r=-r ;;
        esac
    done && shift $((OPTIND - 1))

    local delim=${1:- }
    local item list

    OIFS=$IFS; IFS=$'\n'
    for item in $(sed "s%${delim//%/\%}%\n%g" | sort $r $u); do
        IFS=$OIFS
        list+="$(trim <<<"$item")$delim"
    done

    echo "${list%%$delim}"
}

