#!/usr/bin/env bash
# @import string/trimLines
# @dependency sed cat

squeezeLines()
{
    #
    # Removes all leading/trailing blank lines and condenses all other
    # consecutive blank lines into a single blank line.
    #

    sed '/^[[:space:]]\+$/s/.*//g' | cat -s | trimLines
}
