#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Hello World
# @import console/warn
# @import console/error
# @import example/hello
#
# @dependency bash

main ()
{
    verbose true
    strict true

    _ hello "${HELLO}"
    echo "Script name: $(basename "${BASH_SOURCE[0]}")"
    echo "Caller name: $(basename "$0")"
    echo "Repository : ${MANAGE_REPOSITORY}"
    echo "PWD        : ${PWD}"
    echo "Argument 1 : $1"
    echo "Argument 2 : $2"
    echo "Argument 3 : $3"
}

onExit ()
{
    if (( $1 == 0 ))
    then
        _ warn "Exiting."
    else
        _ error "An error with exit code \"$1\" has occured."
    fi
}

completion () {
    case "$1" in
        reginald)
            echo "Peter"
            echo "Molly:Leading online fashion boutique."
            ;;
        dwayne)
            echo "Map:World maps, atlases and geography."
            echo "News"
            ;;
        files)
            # Fallback to file/dir completion.
            return 1
            ;;
        *)
            echo 'reginald:This is a description for zsh tab completion.'
            echo 'dwayne:This is another description for zsh tab completion.'
            echo 'files:file/dir completion'
        esac
}
