#!/usr/bin/env bash
# @import lang/required
# @import array/includes
# shellcheck disable=SC2034

exists () {
    required "$1" || return 0

    local i
    local dependencies=("$@")
    local coreutils=("sed")
    local code=0

    for i in "${!dependencies[@]}"
    do
        local fails=0
        local names=()

        names+=("${dependencies[i]}")

        if includes coreutils "${dependencies[i]}"
        then
            names+=("g${dependencies[i]}")
        fi

        for name in "${names[@]}"
        do
            command -v "${name}" > /dev/null 2>&1 || fails=$((fails + 1))
        done

        [[ "${fails}" = "${#names[@]}" ]] && code="$((i+1))"
    done

    return "${code}"
}
