#!/usr/bin/env bash
# @import lang/required

exists () {
    required "$1" || return 0

    local i
    local code
    local dependencies=("$@")

    for i in "${!dependencies[@]}"
    do
        if ! command -v "${dependencies[i]}" > /dev/null 2>&1 
        then
            code=$((i+1))
            return "${code}"
        fi
    done
}
