#!/usr/bin/env bash
# @import lang/required
# shellcheck disable=SC2034

repeat()
{
    #
    # Repeat a command a given number of times.
    #

    required "${1}" || return 1

    local count=$1; shift
    local i

    for i in $(seq 1 "${count}"); do
        "$@"
    done
}
