#!/usr/bin/env bash
# @import lang/required
# @import lang/exists
# @import console/die

function checkSha () {
    required "$1" || return 1

    exists openssl || die "Cannot find 'openssl' in path."

    local file="$1"

    if [ -f "${file}" ]
    then
        openssl dgst -sha256 "${file}" | cut -d" " -f 2
    else
        return 1
    fi
}
