#!/usr/bin/env bash
# @import array/includes
# @import lang/required

isInternal ()
{
    required "$1" ||
        return 1

    local internal
    # shellcheck disable=SC2034
    internal=("help" "_manage_help" "lint" "_manage_lint" "_manage_completion" "_manage_shell")
    includes internal "$1"
}
