#!/usr/bin/env bash
# @import array/includes
# @import lang/required

isInternal ()
{
    required "$1" ||
        return 1

    local internal
    # shellcheck disable=SC2034
    internal=("help" "_manage_help" "completion" "_manage_completion" "lint" "_manage_lint")
    includes internal "$1"
}
