#!/usr/bin/env bash
# @import manage/isFile
# @import manage/isMagic
# @import lang/required

#shellcheck disable=SC1001
isScript () {
    local file="$1"

    isFile "${file}" &&
    isMagic "${file}" &&
    [[ "$(basename "${file}")" =~ ^[-a-zA-Z\_]*$ ]]
}
