#!/usr/bin/env bash

manage () {
    if [ "${MANAGE_REPOSITORY}" == "${MANAGE_DIRECTORY}" ]
    then
        "${MANAGE_DIRECTORY}/bin/manage" "$@"
    else
        "${MANAGE_DIRECTORY}/bin/manage" "${MANAGE_REPOSITORY}" "$@"
    fi
}
