#!/usr/bin/env bash

manage () {
    if [ "${MANAGE_REPOSITORY}" == "${MANAGE_DIRECTORY}" ]
    then
        MANAGE_INTERACTIVE=false "${MANAGE_ZERO}" "$@"
    else
        MANAGE_INTERACTIVE=false "${MANAGE_ZERO}" "${MANAGE_REPOSITORY}" "$@"
    fi
}
