#!/usr/bin/env bash
# @import array/includes
# shellcheck disable=SC2034

parseYAML () {
    MANAGE_SCRIPT_DIRECTORY="$(yq '.directories.scripts // "scripts"' "${MANAGE_REPOSITORY}/.manage.yml")"
    MANAGE_SCRIPT_DIRECTORY="${MANAGE_REPOSITORY}/${MANAGE_SCRIPT_DIRECTORY}"

    MANAGE_MODULE_DIRECTORY="$(yq '.directories.modules // "null"' "${MANAGE_REPOSITORY}/.manage.yml")"

    if [[ "${MANAGE_MODULE_DIRECTORY}" == "null" ]]
    then
        MANAGE_MODULE_DIRECTORY="${MANAGE_SCRIPT_DIRECTORY}/modules"
    else
        MANAGE_MODULE_DIRECTORY="${MANAGE_REPOSITORY}/${MANAGE_MODULE_DIRECTORY}"
    fi


    if [[ -z "${MANAGE_PUBLIC}" ]]
    then
        local public
        public="$(yq '.enable // "- help"' "${MANAGE_REPOSITORY}/.manage.yml" | cut -c3-)"

        MANAGE_PUBLIC=(${public})
    fi

    if includes MANAGE_PUBLIC "test"
    then
        MANAGE_TEST_DIRECTORY="$(yq '.directories.tests // "null"' "${MANAGE_REPOSITORY}/.manage.yml")"

        if [[ "${MANAGE_TEST_DIRECTORY}" == "null" ]]
        then
            MANAGE_TEST_DIRECTORY="${MANAGE_SCRIPT_DIRECTORY}/tests"
        else
            MANAGE_TEST_DIRECTORY="${MANAGE_REPOSITORY}/${MANAGE_TEST_DIRECTORY}"
        fi
    fi
}
