#!/usr/bin/env bash

scriptFilter () {
    local script
    local path

    for script in "${!MANAGE_SCRIPTS[@]}"
    do
        path="${MANAGE_SCRIPTS[$script]}"
        if [[ "${script:0:1}" == "_" ]]
        then
            if includes MANAGE_PUBLIC "${script:8}"
            then
                "$1" "${path}"
            fi
        elif [[ "${script}" != "completion" ]]
        then
            "$1" "${path}"
        fi
    done

}
