#!/usr/bin/env bash
# @import console/bgcolor

bar() {
  if test "$2"; then
    for i in "$@"; do
      echo -en "$(bgcolor "$i" " ")"
    done; echo
  else
    for i in {16..21}{21..16}; do
      echo -en "\033[48;5;${i}m \033[0m"
    done; echo
  fi
}

