#!/usr/bin/env bash
# @import lang/required
# @import string/wrap
# @import console/fgcolor
# @import console/attribute
# shellcheck disable=SC2034,SC2016

debug ()
{
    #
    # Will only echo the first argument if verbose mode is disabled.
    # Otherwise, echo the all arguments.
    #

    required "$1" || return 1

    local message
    local arrow
    local level

    arrow="$(attribute bold "$(fgcolor green '>')$(fgcolor)")$(attribute)"
    level="$(attribute bold "$(fgcolor green 'DEBUG')$(fgcolor)")$(attribute)"

    local arguments=("$@")
    message="$(join arguments $'\n\n')"

    message="${message//$HOME/~}"

    verbose && {
        echo -n "${level} "
        wrap "${message}" 76 | sed "2,\${s/^/${arrow} /}"
    }
}
