#!/usr/bin/env bash
# @import console/error

die ()
{
    #
    # Displays an error message and exits with the given error code.
    #
    # Usage: _die [MESSAGE] [ERROR]
    #

    verbose true
    error "$1"; exit "${2:-1}"
}
