#!/usr/bin/env bash
#
# Copyright (c) 2017 Mark Milstein <mark@epiloque.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @import console/error

die ()
{
    verbose true
    error "$1"; exit "${2:-1}"
}
