#!/usr/bin/env bash

icon() {
    local i='';
    case "$1" in
        check|checkmark)       i='\xE2\x9C\x93';;
        X|x|xmark)             i='\xE2\x9C\x98';;
        '<3'|heart)            i='\xE2\x9D\xA4';;
        sun)                   i='\xE2\x98\x80';;
        '*'|star)              i='\xE2\x98\x85';;
        darkstar)              i='\xE2\x98\x86';;
        umbrella)              i='\xE2\x98\x82';;
        flag)                  i='\xE2\x9A\x91';;
        snow|snowflake)        i='\xE2\x9D\x84';;
        music)                 i='\xE2\x99\xAB';;
        scissors)              i='\xE2\x9C\x82';;
        tm|trademark)          i='\xE2\x84\xA2';;
        copyright)             i='\xC2\xA9';;
        apple)                 i='\xEF\xA3\xBF';;
        skull|bones)           i='\xE2\x98\xA0';;
        ':-)'|':)'|smile|face) i='\xE2\x98\xBA';;
    esac
    echo -ne "$i";
}
