#!/usr/bin/env bash
#
# Copyright (c) 2017 Mark Milstein <mark@epiloque.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @import console/attribute
# @import console/error
# @import console/info
# @import console/debug
# @import console/warn
# @import lang/required
# @import string/wrap
# @import array/join
# shellcheck disable=SC2034,SC2016


log ()
{
    #
    # Will only echo the first argument if verbose mode is disabled.
    # Otherwise, echo the all arguments.
    #

    required "$1" || return 1

    local message
    local arrow
    arrow="$(attribute bold ">")$(attribute)"

    case "$1" in
        debug)
            shift

            debug "${@}"
            ;;
        info)
            shift

            info "${@}"
            ;;
        warn)
            shift

            warn "${@}"
            ;;
        error)
            shift

            error "${@}"
            ;;
        *)
            if verbose
            then
                local arguments=("$@")
                message="$(join arguments $'\n\n')"
            else
                message="$1"
            fi

            wrap "${message}" 76 | sed "2,\${s/^/${arrow} /}"
    esac
}
