#!/usr/bin/env bash
# @import console/attribute
# @import console/error
# @import console/info
# @import console/warn
# @import lang/required
# @import string/wrap
# shellcheck disable=SC2034,SC2016


log ()
{
    #
    # Will only echo the first argument if verbose mode is disabled.
    # Otherwise, echo the all arguments.
    #

    required "$1" || return 1

    local message
    local arrow
    arrow="$(attribute bold ">")$(attribute)"

    case "$1" in
        info)
            shift

            info "${@}"
            ;;
        warn)
            shift

            warn "${@}"
            ;;
        error)
            shift

            error "${@}"
            ;;
        *)
            if verbose
            then
                local arguments=("$@")
                message="$(join arguments $'\n\n')"
            else
                message="$1"
            fi

            wrap "${message}" 76 | sed "2,\${s/^/${arrow} /}"
    esac
}
