#!/usr/bin/env bash

log()
{
    #
    # Will only echo the first argument if verbose mode is disabled.
    # Otherwise, echo the all arguments.
    #
    # Usage: log [TRUE_VALUE] [FALSE_VALUE]
    #

    if verbose
    then
        echo "$@"
    else
        echo "$1"
    fi
}
