#!/usr/bin/env bash
# @import lang/required
# @import console/attribute
# @import console/fgcolor
# @import string/wrap
# @dependency sed

# TODO: stdout/stderr and verbose handling

message()
{
    #
    # Displays a colorized (if available) informational message.
    #

    if ! verbose
    then
        return
    fi

    required "$1" "$2" ||
        return 0

    local msg
    local color
    local level

    level="$1"
    shift
    msg="$*"
    msg=${msg//$HOME/\~}
    # shellcheck disable=SC2016
    msg="$(echo "${msg}" | wrap | sed '2,${s/^/          /}')"

    case "${level}" in
        WARN)
            color="yellow"
            level="WARN "
            ;;
        ERROR)
            color="red"
            level="ERROR"
            ;;
        INFO)
            color="blue"
            level="INFO "
            ;;
        *)
            return 0
    esac

    >&2 echo "$(attribute bold)${level} $(fgcolor ${color})==>$(fgcolor)$(attribute) ${msg}"
}
