#!/usr/bin/env bash
# @import lang/required
# @import string/wrap
# @import console/fgcolor
# @dependency sed
# shellcheck disable=SC2034,SC2016

warn ()
{
    #
    # Will only echo the first argument if verbose mode is disabled.
    # Otherwise, echo the all arguments.
    #

    required "$1" || return 1

    local message
    local arrow
    local level

    arrow="$(attribute bold "$(fgcolor yellow '>')$(fgcolor)")$(attribute)"
    level="$(attribute bold "$(fgcolor yellow 'WARN')$(fgcolor)")$(attribute)"

    if verbose
    then
        local arguments=("$@")
        message="$(join arguments $'\n\n')"
    else
        message="$1"
    fi

    message="${message//$HOME/~}"

    >&2 echo -n "${level} " >&2
    wrap "${message}" 76 | sed "2,\${s/^/${arrow} /}" >&2
}
