#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# Manage tab completions
#
# </doc>

getcompletions () {
    if (( $# == 0 ))
    then
        scriptEach filter scriptDescription
    else
        name="$1"
        #shellcheck disable=SC2034
        MANAGE_COMPLETION="true"
        if _ includes MANAGEPUBLIC "${name}"
        then
            swaprun "$@"
        elif exists "${name}"
        then
            shift
            prepare "${name}" "$@"
        fi
    fi
}

main ()
{
    cache getcompletions "$@"
}
