#!/usr/bin/env bash
# @description Display this help and exit

main ()
{
    strict true

    help "$1"
}

# completion () {
#     if (( $# == 0 ))
#     then
#         scriptEach filter scriptDescription
#     fi
# }
