#!/usr/bin/env bash

_manage_completions() {
    COMPREPLY=()
    local word="${COMP_WORDS[COMP_CWORD]}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$(manage completion | sed 's/:.*//' )" -- "$word") )
    else
        local command="${COMP_WORDS[1]}"
        local completions

        if [[ -z "${COMP_WORDS[@]:2}" ]]
        then
            completions="$(manage completion "${command}" | sed 's/:.*//' )"
        else
            completions="$(manage completion "${command}" "${COMP_WORDS[@]:2}" | sed 's/:.*//' )"
        fi

        [ ! -n "${completions}" ] && return 1

        COMPREPLY=( $(compgen -W "$completions" -- "$word") )
    fi
}

__manage_complete ()
{
    local _mc="_manage_completions"
    complete -o bashdefault -o default -o nospace -F "${_mc}" "$1" 2>/dev/null \
    || complete -o default -o nospace -F "${_mc}" "$1"
}
