#!/usr/bin/env zsh

_manage_fallback () {
    if zstyle -T ":completion:${curcontext}:" use-fallback; then
        _path_files
        ret=$?
    else
        _message 'Unknown sub-command'
    fi
}

_manage () {
    _arguments -C \
        '1:script:->scripts' \
        '*:: :->args' \
        && ret=0

    local _script
    local -a _names
    local completions
    key="$(pwd | md5sum)"
    key="_manage_zsh_${key[0,32]}"

    scripts=("${(@f)$(manage completion)}")

    for _script in $scripts[@]
    do
        _script=("${(s/:/)_script}")
        _names+=("${_script[1]}")
    done

    case "$state" in
        (scripts)
            _describe -t scripts 'scripts' scripts && ret=0
            ;;
        (args)
            if (( ${_names[(I)${line[1]}]} ))
            then
                if  [[ -z "${line[@]:1}" ]]
                then
                    completions=("${(@f)$(manage completion "${line[1]}")}")
                else
                    completions=("${(@f)$(manage completion "${line[1]}" "${line[@]:1}")}")
                fi

                if  [ -z "${completions}" ]
                then
                    _manage_fallback
                else
                    _describe -t completions "${line[1]}" completions && ret=0
                fi
            else
                _manage_fallback
            fi
            ;;
    esac

    return 1
}
