#!/usr/bin/env bash
#
# <doc>
#
# A simple Hello World script.
#
# </doc>
#
# <import>
#
# collection-shell
#
# </import>


main () {
    strict false
    cat /tmp/thisfiledoesnotexistsdoesit > /dev/null 2>&1
}

onexit () {
    echo "onexit $1"
}
