#!/usr/bin/env bash
#
# <doc>
#
# A simple Hello World script.
#
# </doc>
#
# <import>
#
# collection-shell
#
# </import>


main () {
    strict true
    echo "Hello World" > /dev/null
}

onexit () {
    echo "onexit $1"
}
