#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# Bootstrap manage repository in the current directory
#
# </doc>
#
# <import>
#
# collection-shell
# collection-string
# collection-message
# collection-file
# collection-tag
#
# </import>

_managePath () {
    local destinationpath
    local sourcepath
    local path
    destinationpath="$1"
    sourcepath="$(pwd)"
    path="$(_ relpath "${destinationpath}" "${sourcepath}")"
    if [[ "${path}" == ".." ]] ||
       [[ "${path}" == "."  ]]
    then
        _ die "Consider a path outside of the manage repository."
    else
        echo "${path}"
    fi
}

_scriptPath () {
    local scriptdir
    local managedir
    local absmanagedir
    local absscriptdir
    local checkcommon

    [ -n "$2" ] && scriptdir="$2" || scriptdir="script"
    [ -n "$1" ] && managedir="$1" || _ die

    absmanagedir="$(_ abspath "${managedir}")"
    absscriptdir="$(_ abspath "${scriptdir}")"
    checkcommon="$(_ commonpath "${absmanagedir}" "${absscriptdir}")"
    if [ "${checkcommon}" == "${absmanagedir}" ]
    then
        _ die "Consider a path outside of the manage repository."
    else
        echo "${scriptdir}"
    fi
}

main () {
    strict true

    local T_MANAGEDIRECTORY
    local T_MANAGESCRIPTSDIRECTORY

    T_MANAGEDIRECTORY="$(_managePath "${MANAGEDIRECTORY}")"
    T_MANAGESCRIPTSDIRECTORY="$(_scriptPath "${T_MANAGEDIRECTORY}" "$(echo "$*" | _ joinLines " ")")"

    _ info "Absolute path to manage directory $(_ abspath "${T_MANAGEDIRECTORY}")"
    _ info "Absolute path to script directory $(_ abspath "${T_MANAGESCRIPTSDIRECTORY}")"

    if [ ! -d "${T_MANAGESCRIPTSDIRECTORY}" ];
    then
        _ info "Creating script directory $(_ abspath "${T_MANAGESCRIPTSDIRECTORY}")"
        mkdir "${T_MANAGESCRIPTSDIRECTORY}"
    fi
    mkdir "${PWD}/test"

    cp -Lf "${T_MANAGEDIRECTORY}/template/hello"        "${T_MANAGESCRIPTSDIRECTORY}/hello"
    cp -Lf "${T_MANAGEDIRECTORY}/template/test"         "${T_MANAGESCRIPTSDIRECTORY}/test"
    cp -Lf  "${T_MANAGEDIRECTORY}/template/manage.yml"  "${PWD}/.manage.yml"
    cp -Lf  "${T_MANAGEDIRECTORY}/template/helper.bash" "${PWD}/test/helper.bash"
    cp -Lf  "${T_MANAGEDIRECTORY}/template/hello.bats"  "${PWD}/test/hello.bats"
    ln -s  "${T_MANAGEDIRECTORY}/libexec/manage"        "${PWD}/manage"
}

