#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# ShellCheck manage
#
# </doc>

main ()
{
    verbose true
    strict true

    local file
    local paths=(${MANAGEIMPORTPATHS[@]})

    find \
        "${MANAGESCRIPTDIRECTORY}" \
        -type f -print0 |
        while read -d '' -r file
        do
            isscript "${file}" && shellcheck "${file}"
        done

    for ((i=0;i<${#paths[@]};i++))
    do
        paths[i]="${paths[i]}/*"
    done

    for file in ${paths[*]}
    do
        shellcheck "${file}"
    done

}

onexit ()
{
    if (( $1 != 0 ))
    then
        _ error "An error with exit code \"$1\" has occured."
    fi
}
