#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# Run the test suite
#
# </doc>
#
# <import>
#
# collection-shell
# collection-message
#
# </import>
#
# <dependency>
#
# bats
#
# </dependency>

main () {
    local name
    local file
    export MANAGEDIRECTORY
    export MANAGEREPOSITORY
    export MANAGEMANAGETESTDIRECTORY

    if [ -d "${MANAGETESTDIRECTORY}" ]
    then
        if _ required "${1}"
        then
            for file in "${MANAGETESTDIRECTORY}"/*.bats
            do
                if [   -f "${file}" ] &&
                   [   -r "${file}" ]
                   [[ "$(basename "${file}")" == *.bats ]]
                then
                    name="$(basename "${file}")"
                    if [[ "${1}" == "${name::-5}" ]]
                    then
                        bats "$(_ truthEcho "${CI}" "--tap" "--pretty")" "${file}"
                    fi
                fi
            done
            cd "${OPWD}" || exit
        else
            bats "$(_ truthEcho "${CI}" "--tap" "--pretty")" "${MANAGETESTDIRECTORY}"
        fi
    else
        _ die "No tests, aborting."
    fi
}

