#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# YAML-like parser
#
# </doc>
#
# <import>
#
# collection-yaml
#
# </import>
#

main () {
    strict
    echo "$(_ yaml "${MANAGEDIRECTORY}/.manage.yml" "rer")"
    eval "$(_ yaml "${MANAGEDIRECTORY}/.manage.yml" "rer")"
    rer test ' '
}
