#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# A simple YAML-like parser.
#
# </doc>
#
# <import>
#
# collection-shell
# libexec-yaml
#
# </import>
#

main () {
    _strict true
    YAML="$(parseyaml "${MANAGEDIRECTORY}"/.manage.yml)"
    eval "$(yaml "${YAML}" default strict qweqwe dependencies)"
    echo "${DEFAULT}"
    echo "${DEPENDENCIES[@]}"
}
