#!/usr/bin/env bash
# @import lang/required
# @import array/join
# @import array/includes

complement () {
    required "$1" "$2" ||
        return 1
    local A="$1[@]"
    local B="$2[@]"
    local AdB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        if ! includes "$2" "${itema}"
        then
            AdB+=( "$itema" )
        fi
    done

    for itemb in "${!B}"; do
        if ! includes "$1" "${itemb}"
        then
            AdB+=( "$itemb" )
        fi
    done

    join AdB "$3"
}
