#!/usr/bin/env bash
# @import lang/required
# @import array/join
# @import array/includes

difference () {
    required "$1" "$2" ||
        return 1

    local A="$1[@]"
    local B="$2[@]"
    local AcB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        if ! includes "$2" "${itema}"
        then
            AcB+=( "$itema" )
        fi
    done

    join AcB "$3"
}

