#!/usr/bin/env bash
# @import lang/required

forEach () {
    #TODO: this runs in a subshell
    # try
    # for i in "${!array[@]}"
    #
    required "$1" "$2" ||
        return 1

    local array="$1[@]"
    local function=$2
    shift 2
    local in=0

    for element in "${!array}"
    do
        "${function}" "${in}" "$@"
        in=$((in+1))
    done
}

