#!/usr/bin/env bash
# @import lang/required

includes () {
    required "$1" "$2" ||
        return 1

    local array="$1[@]"
    local seeking=$2
    local element
    for element in "${!array}"; do
        if [[ "${element}" == "${seeking}" ]]; then
            return 0
            break
        fi
    done
    return 1
}
