#!/usr/bin/env bash
# @import lang/required

join ()
{
    required "$1" ||
        return 1

    local array="$1[*]"
    local OIFS="${IFS}"
    if [ ! -z "$2" ]
    then
        local IFS="$2"
    else
        local IFS=$'\n'
    fi
    echo "${!array}"
    IFS="${OIFS}"
}
