#!/usr/bin/env bash

# Filename:      collection-array
# Description:   Array manipulation helpers

[[ $COLLECTION_ARRAY_LOADED ]] && return

source collection-shell

_join ()
{
    _required "$1" ||
        return 1

    local array="$1[*]"
    local OIFS="${IFS}"
    if [ ! -z "$2" ]
    then
        local IFS="$2"
    else
        local IFS=$'\n'
    fi
    echo "${!array}"
    IFS="${OIFS}"
}

_includes () {
    _required "$1" "$2" ||
        return 1

    local array="$1[@]"
    local seeking=$2
    local element
    for element in "${!array}"; do
        if [[ "${element}" == "${seeking}" ]]; then
            return 0
            break
        fi
    done
    return 1
}

_indexOf () {
    _required "$1" "$2" ||
        return 1

    local array="$1[@]"
    local seeking=$2
    local in=0
    for element in "${!array}"; do
        if [[ "${element}" == "${seeking}" ]]; then
            echo "${in}"
            break
        fi
        in=$((in+1))
    done
}

_forEach () {
    _required "$1" "$2" ||
        return 1

    local array="$1[@]"
    local function=$2
    shift 2
    local in=0
    for element in "${!array}"; do
        "${function}" "${in}" "$@"
        in=$((in+1))
    done
}

_intersection () {
    _required "$1" "$2" ||
        return 1

    local A="$1[@]"
    local B="$2[@]"
    local AiB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        for itemb in "${!B}"; do
            if [[ "${itema}" == "${itemb}" ]]; then
                AiB+=( "$itema" )
                break
            fi
        done
    done

    _join AiB "$3"
}

_difference () {
    _required "$1" "$2" ||
        return 1
    local A="$1[@]"
    local B="$2[@]"
    local AdB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        if ! _includes "$2" "${itema}"
        then
            AdB+=( "$itema" )
        fi
    done

    for itemb in "${!B}"; do
        if ! _includes "$1" "${itemb}"
        then
            AdB+=( "$itemb" )
        fi
    done

    _join AdB "$3"
}

_complement () {
    _required "$1" "$2" ||
        return 1

    local A="$1[@]"
    local B="$2[@]"
    local AcB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        if ! _includes "$2" "${itema}"
        then
            AcB+=( "$itema" )
        fi
    done

    _join AcB "$3"
}

_union () {
    _required "$1" "$2" ||
        return 1

    local A="$1[@]"
    local B="$2[@]"
    local itema
    local itemb

    for itema in "${!A}"; do
        AuB+=( "$itema" )
    done

    for itemb in "${!B}"; do
        AuB+=( "$itemb" )
    done

    _join AuB "$3"
}

COLLECTION_ARRAY_LOADED=1
