#!/usr/bin/env bash

[[ $COLLECTION_YAML_LOADED ]] && return

source collection-shell
source collection-string
source collection-array

_yaml() {
    #
    # YAML-like parser
    #
    # Usage: _ yaml FILENAME FUNCTIONNAME
    #

    _required "$1" "$2" ||
        return 1

    [ -f "$1" ] ||
        return 1

    #shellcheck disable=SC1001
    [[ "$2" =~ ^[-a-zA-Z\_]*$ ]] ||
        return 1

    local parsed
    local s w fs
    s='[[:space:]]*'
    w='[a-zA-Z0-9_]*'
    fs="$(echo @|tr @ '\034')"

    parsed="$(
        sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
            -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |

        awk -F"$fs" '{
            indent = length($1)/2;
            vname[indent] = $2;
            for (i in vname) {if (i > indent) {delete vname[i]}}
                if (length($3) > 0) {
                    vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
                    printf("%s%s%s=(\"%s\")\n", "",vn, $2, $3);
                }
        }' |
        sed 's/_=/+=/g' |
        grep -E '^[a-zA-Z0-9_]+(\+\=|\=)\(\".+\"\)'   |
        sed 's/[a-zA-Z0-9_]\+[\+\=]/\L&/g'
    )"

    if _required "${parsed}"
    then
        local variable
        local result
        variables=($(echo "${parsed}" |
                    sed 's/+=.*$//' |
                    sed 's/=.*$//'  |
                    sort -u))


        if (( ${#variables[@]} != 0 ))
        then
            result="$(
                echo "${2} () {" \
                'local __keys=('"$(_ join variables ' ')"')'
                for variable in "${variables[@]}"
                do
                    echo "local ${variable}"
                    echo "${parsed}" |
                    grep -E "^${variable}(\+\=|\=)"
                done
                echo "_ join \"\$1\" \"\$2\""
                echo '}'
            )"
            echo "${result}"
        fi
    fi
}

COLLECTION_YAML_LOADED=1
