#!/usr/bin/env bash

# Filename:      collection-grammar
# Description:   Functions for manipulating & parsing scripts.
#

[[ $COLLECTION_GRAMMAR_LOADED ]] && return

source collection-string

_actions()
{
    #
    # Show all functions that are prefixed with PREFIX (stripped off).
    # If no [FILE...] is provided functions are looked up in the running stack.
    #
    # Usage:
    #
    # _actions [PREFIX] [FILE]
    # cat | [FILE] | _actions [PREFIX]
    #

    local name="$1"
    shift
    if [ -t 0 ] && [ -z "${*}" ]
    then
        declare -F | awk '{print $NF}' |
        grep "^${name}" |
        sort -u
    else
        _functions "$@" |
        grep "^${name}" |
        sort -u
    fi
}

_embeddedRange()
{
    #
    # Get embedded text between a given range.
    #
    # Usage: embeddedRange START END [FILE...]
    #

    local s=${1//\//\\/}; shift
    local e=${1//\//\\/}; shift
    local c="^[[:space:]]*#[[:space:]]*"

    sed -n "/$c$s/,/$c$e/p" "$@" | sed '1d;$d' | sed "s/$c//" | _squeezeLines
}

_embeddedTag()
{
    #
    # Get the embedded text between a start and end XML-like tag.
    #
    # Usage: _embeddedTag NAME
    #

    local name=$1; shift
    _embeddedRange "<$name>" "</$name>" "$@"
}


_embeddedEval()
{
    #
    # Eval embedded code contained in a given tag.
    #
    # Usage: _embeddedEval NAME [FILE...]
    #

    local name=$1; shift
    eval "$(_embeddedTag "$name" "$@")"
}

_functions()
{
    #
    # Pulls all function names from file.
    #
    # Usage: _functions [FILE]
    #

    _lines "$@" | _trim |
    grep -E '^[a-zA-Z0-9_-]+[[:space:]]*[\(]{1}[\)]{1}' |
    sed 's/().*$//' | _trim | sort -u
}

_lines()
{
    #
    # Get all lines except for comments and blank lines.
    #
    # Usage: _lines [FILE...]
    #

    grep -E -v '^[[:space:]]*#|^[[:space:]]*$' "$@"
}


_variables()
{
    #
    # Pulls all variable names from stdin.
    #

    sed 's/[[:space:];]/\n/g' "$@"    |
    grep -E '^[a-zA-Z0-9_]+(\+\=|\=)' |
    sed 's/+=.*$//' |
    sed 's/=.*$//'  |
    sort -u
}

COLLECTION_GRAMMAR_LOADED=1
