#!/usr/bin/env bash

# Filename:      collection-messages
# Description:   A set of functions for giving the user information.

[[ $COLLECTION_MESSAGE_LOADED ]] && return

source collection-shell
source collection-string
source collection-markup

_echo()
{
    #
    # Will only echo the first argument if verbose mode is enabled.
    # Otherwise, echo the second argument.
    #
    # Usage: _echo [TRUE_VALUE] [FALSE_VALUE]
    #

    if verbose
    then
        echo "$1"
    else
        echo "$2"
    fi
}

_die()
{
    #
    # Displays an error message and exits with the given error code.
    #
    # Usage: _die [MESSAGE] [ERROR]
    #

    verbose true
    _error "$1"; exit "${2:-1}"
}

__message()
{
    #
    # Displays a colorized (if available) informational message.
    #

    if ! verbose
    then
        return
    fi

    _required "$1" "$2" ||
        return 0

    local msg
    local color
    local level

    level="$1"
    shift
    msg="$*"
    msg=${msg//$HOME/\~}
    # shellcheck disable=SC2016
    msg="$(echo "${msg}" | _wrap | sed '2,${s/^/          /}')"

    case "${level}" in
        WARN)
            color="yellow"
            level="WARN "
            ;;
        ERROR)
            color="red"
            level="ERROR"
            ;;
        INFO)
            color="blue"
            level="INFO "
            ;;
        *)
            return 0
    esac

    >&2 echo "$(_a bold)${level} $(_c ${color})==>$(_c)$(_a) ${msg}"
}

_info()
{
    __message INFO "$@"
}

_warn()
{
    __message WARN "$@"
}

_error()
{
    __message ERROR "$@"
}

COLLECTION_MESSAGE_LOADED=1
