#!/usr/bin/env bash

# Filename:      collection-shell-trap
# Description:   Bash exceptions.

[[ $COLLECTION_SHELL_TRAP_LOADED ]] && return

_exceptionHandler () {
    local trap_name="$1"
    echo "ERROR: ${trap_name} on line $( caller )" >&2 ; _exit 1
}

_catchExceptions () {
    trap '_exceptionHandler "SIGERR" ${LINENO} ${$?}' ERR
    trap '_exceptionHandler "SIGINT" ${LINENO} ${$?}' INT
    trap '_exceptionHandler "SIGHUP" ${LINENO} ${$?}' HUP
    trap '_exceptionHandler "SIGTERM "${LINENO} ${$?}' TERM
    trap '_exceptionHandler "SIGKILL" ${LINENO} ${$?}' KILL
    trap '_exceptionHandler "SIGQUIT" ${LINENO} ${$?}' QUIT
}

COLLECTION_SHELL_TRAP_LOADED=1
