#!/usr/bin/env bash

# Filename:      collection-utils
# Description:   Functions for manipulating & parsing scripts.
#

[[ $COLLECTION_TAG_LOADED ]] && return

source collection-shell
source collection-string

_actions()
{
    #
    # Show all functions that are prefixed with PREFIX (stripped off).
    # If no [FILE...] is provided functions are looked up in  the running stack.
    #
    # Usage:
    #
    # _actions [PREFIX] [FILE]
    # cat | [FILE] | _actions [PREFIX]
    #

    local name="$1"
    shift
    if [ -t 0 ] && [ -z "${*}" ]
    then
        declare -F | awk '{print $NF}' |
        grep "^${name}" |
        sort -u
    else
        _functions "$@" |
        grep "^${name}" |
        sort -u
    fi
}

_embeddedRange()
{
    #
    # Get embedded text between a given range.
    #
    # Usage: embeddedRange START END [FILE...]
    #

    local s=${1//\//\\/}; shift
    local e=${1//\//\\/}; shift
    local c="^[[:space:]]*#[[:space:]]*"

    sed -n "/$c$s/,/$c$e/p" "$@" | sed '1d;$d' | sed "s/$c//" | _squeezeLines
}

_embeddedTag()
{
    #
    # Get the embedded text between a start and end XML-like tag.
    #
    # Usage: _embeddedTag NAME
    #

    local name=$1; shift
    _embeddedRange "<$name>" "</$name>" "$@"
}


_embeddedEval()
{
    #
    # Eval embedded code contained in a given tag.
    #
    # Usage: _embeddedEval NAME [FILE...]
    #

    local name=$1; shift
    eval "$(_embeddedTag "$name" "$@")"
}

_functions()
{
    #
    # Pulls all function names from file.
    #
    # Usage: _functions [FILE]
    #

    _lines "$@" | _trim |
    grep -E '^[a-zA-Z0-9_-]+[[:space:]]*[\(]{1}[\)]{1}' |
    sed 's/().*$//' | _trim | sort -u
}

_lines()
{
    #
    # Get all lines except for comments and blank lines.
    #
    # Usage: _lines [FILE...]
    #

    grep -E -v '^[[:space:]]*#|^[[:space:]]*$' "$@"
}

_mustache()
{
    #
    # Substitute variable names with variables in a file.
    #
    # The default is to try to substitute all environment variables, but if
    # any names are given, it will be limited to just those.
    #
    # The placeholder syntax can be changed by setting the following variables:
    #
    #     MUSTACHE_L  # Default: {{
    #     MUSTACHE_R  # Default: }}
    #
    # Usage: _mustache FILE [VAR...]
    #

    local fn=$1; shift

    [[ -f $fn ]] || return 1

    local n

    local fl=${MUSTACHE_L:-\{\{}
    local fr=${MUSTACHE_R:-\}\}}

    if (( $# == 0 )); then
        IFS=$'\n' set -- $(set | _variables)
    fi

    for n in "$@"; do
        sed -i "s%${fl}${n//%/\%}${fr}%${!n}%g" "$fn"
    done
}

_variables()
{
    #
    # Pulls all variable names from stdin.
    #

    sed 's/[[:space:];]/\n/g' "$@" |
    egrep '^[a-zA-Z0-9_]+=' |
    sed 's/=.*$//' | sort -u
}

COLLECTION_TAG_LOADED=1
