#!/usr/bin/env bash

[[ $COLLECTION_TAG_LOADED ]] && return

source collection-string

__tag()
{

    local s=${1//\//\\/}; shift
    local e=${1//\//\\/}; shift
    local c="^[[:space:]]*#[[:space:]]*"

    sed -n "/$c$s/,/$c$e/p" "$@" | sed '1d;$d' | sed "s/$c//" | _squeezeLines
}

_tag()
{
    #
    # Get the embedded text between a start and end XML-like tag.
    #
    # Usage: _ tag NAME
    #

    local name=$1; shift
    __tag "<$name>" "</$name>" "$@"
}

COLLECTION_TAG_LOADED=1
