#!/usr/bin/env bash

# Filename:      collection-array
# Description:   Array manipulation helpers

[[ $COLLECTION_ARRAY_LOADED ]] && return


source collection-shell

_includes () {
    local array="$1[@]"
    local seeking=$2
    local element
    for element in "${!array}"; do
        if [[ "${element}" == "${seeking}" ]]; then
            return 0
            break
        fi
    done
    return 1
}

_indexOf () {
    local array="$1[@]"
    local seeking=$2
    local in=0
    for element in "${!array}"; do
        if [[ "${element}" == "${seeking}" ]]; then
            echo "${in}"
            break
        fi
        in=$((in+1))
    done
}

_forEach () {
    local array="$1[@]"
    local function=$2
    local in=0
    for element in "${!array}"; do
        "${function}" "${in}"
        in=$((in+1))
    done
}

_count () {
    local array="$1[@]"
    local in=0
    for element in "${!array}"; do
        in=$((in+1))
    done
    echo "${in}"
}

_get () {
    local array="$1[@]"
    local seeking=$2
    local in=0
    for element in "${!array}"; do
        if [[ "${in}" == "${seeking}" ]]; then
            echo "${element}"
            break
        fi
        in=$((in+1))
    done
}

_intersection () {
    _required "$1" "$2" || return 1

    local A="$1[@]"
    local B="$2[@]"
    local AiB=()
    local itema
    local itemb

    for itema in "${!A}"; do
        for itemb in "${!B}"; do
            if [[ "${itema}" == "${itemb}" ]]; then
                AiB+=( "$itema" )
                break
            fi
        done
    done

    echo "${AiB[*]}"
}

_difference () {
    _required "$1" "$2" || return 1
    local intersection
    local A="$1[@]"
    local B="$2[@]"
    local AdB=()
    local itema
    local itemb

    intersection=($(_intersection "$1" "$2"))

    for itema in "${!A}"; do
        if ! _includes intersection "${itema}"
        then
            AdB+=( "$itema" )
        fi
    done

    for itemb in "${!B}"; do
        if ! _includes intersection "${itemb}"
        then
            AdB+=( "$itemb" )
        fi
    done

    echo "${AdB[*]}"
}

#TODO: union

COLLECTION_ARRAY_LOADED=1
