#!/usr/bin/env bash

manage () {
    if [ "${MANAGEREPOSITORY}" == "${MANAGEDIRECTORY}" ]
    then
        "${MANAGEDIRECTORY}/libexec/manage" "$@"
    else
        "${MANAGEDIRECTORY}/libexec/manage" "${MANAGEREPOSITORY}" "$@"
    fi
}

_main ()
{
    PATH="${MANAGEDIRECTORY}/vendor/bats/libexec:$PATH"
    local _code
    local _function
    if [ -n "${MANAGECOMPLETION}" ]
    then
        _function="completion"
    else
        _function="main"
    fi
    if declare -f "${_function}" > /dev/null 2>&1
    then
        trap '__ once _return $?' INT HUP TERM KILL QUIT EXIT
        "${_function}" "$@"
        _code=$?
        trap - INT HUP TERM KILL QUIT EXIT ERR
    fi

    __ once _return "${_code}"
    return $?
}

_return ()
{
    local _code=${1:-0}
    if declare -f "onexit" > /dev/null 2>&1
    then
        onexit "${_code}" || true
    fi

    return "${_code}"
}
