#!/usr/bin/env bash
#
# <doc>
#
# A simple Hello World script.
#
# </doc>
#
# <import>
#
# collection-shell
#
# </import>


main () {
    _strict true

    true
    return 45
    true
}

onexit () {
    echo "onexit $1"
}
