#!/usr/bin/env bash
# @import manage/dockerBuild
# @import manage/downloadDumbInit
# @import manage/manage
# vim: set ft=sh:
# @description Lint & test in a docker container

dockerTest ()
{
    IMAGE="${DOCKER_SCOPE:-internal}/$1"

    _ downloadDumbInit
    _ dockerBuild "$1"

    docker run \
        -e "TEST_SUITE=${TEST_SUITE}" \
        --rm "${IMAGE}" _manage_ci
}

main () {
    verbose true
    strict true

    if [[ "${DOCKER}" == "true" ]]
    then
        case "${TEST_SUITE}" in
            lint)
                _ manage lint
            ;;
            *)
                _ manage test
        esac

    elif [[ "${TRAVIS}" == "true" ]]
    then
        case "${TEST_SUITE}" in
            lint)
                dockerTest shellcheck
            ;;
            fedora)
                dockerTest fedora
            ;;
            osx)
                _ manage test
            ;;
            *)
                exit 1
        esac
    else
        _ die "not running in a CI environment"
    fi
}
