#!/usr/bin/env bash
# @import manage/dockerBuild
# @import manage/downloadDumbInit
# @import manage/manage
# @import lang/required
# @import console/die
# @import lang/first
# vim: set ft=sh:
# @description Lint & test in a docker container

dockerTest ()
{
    IMAGE="${DOCKER_SCOPE:-internal}/$1"

    _ downloadDumbInit
    _ dockerBuild "$1"

    docker run \
        -e "TEST_SUITE=${TEST_SUITE}" \
        --rm "${IMAGE}" _manage_ci
}

main () {
    verbose true
    strict true

    TEST_SUITE="$(_ first "${TEST_SUITE}" "$1")" || _ die "No test suite chosen"

    if [[ "${DOCKER}" == "true" ]]
    then
        case "${TEST_SUITE}" in
            lint)
                _ manage lint
            ;;
            *)
                _ manage test
        esac
    else
        case "${TEST_SUITE}" in
            lint)
                dockerTest shellcheck
            ;;
            fedora)
                dockerTest fedora
            ;;
            alpine)
                dockerTest alpine
            ;;
            osx)
                _ manage test
            ;;
            *)
                _ die "'${TEST_SUITE}' is not a valid test suite"
        esac
    fi
}
