#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Lint script & modules

main ()
{
    verbose true
    strict true

    local file
    local paths
    local exitCode=0

    # if required "$1"
    # then
    #     paths=($@)
    if [[ "${MANAGE_REPOSITORY}" == "${MANAGE_DIRECTORY}" ]]
    then
        paths=(${MANAGE_IMPORT_PATHS[@]} "${MANAGE_SCRIPT_DIRECTORY}")
    else
        # TODO: lint non manage repositories
        paths=(${MANAGE_IMPORT_PATHS[@]}/"${MANAGE_DIRECTORY}/modules")
    fi

    while read -d '' -r file
    do
        isScript "${file}" && shellcheck "${file}" || exitCode=$?
    done < <(find "${paths[@]}" -type f -print0)

    exit "${exitCode}"
}
