#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description import and trust Escapace GPG key
# @import manage/sendKey

main ()
{
    verbose true
    strict true

    local id="D52633612B824195696B80D690A65F3603169487"

    _ sendKey "${id}"
}
