#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Load manage into shell

getShell ()
{
    basename "/${SHELL}"
}

main ()
{
    strict true
    local init
    local shell
    local profile

    if required "$1"
    then
        if [[ "$1" == "-" ]]
        then
            shell="$(getShell)"
        else
            shell="$1"
        fi
    else
        shell="help"
    fi

    case "${shell}" in
        bash)
            echo "PATH=\"${MANAGE_DIRECTORY}/libexec:\$PATH\""

            cat "${MANAGE_DIRECTORY}/scripts/shell/completions/bash"

            echo "complete -F _manage -o default manage"

            if [[ "$(basename "${MANAGE_ZERO}")" != "manage" ]]
            then
                echo "complete -F _manage -o default $(basename "${MANAGE_ZERO}")"
            fi
            ;;
        zsh)
            echo "PATH=\"${MANAGE_DIRECTORY}/libexec:\$PATH\""

            cat "${MANAGE_DIRECTORY}/scripts/shell/completions/zsh"

            echo "compdef _manage manage"

            if [[ "$(basename "${MANAGE_ZERO}")" != "manage" ]]
            then
                echo "compdef _manage manage $(basename "${MANAGE_ZERO}")"
            fi
            ;;
        help)
            case "$(getShell)" in
                bash)
                    profile='~/.bash_profile'
                    init="bash"
                    ;;
                zsh)
                    profile='~/.zshenv'
                    init="zsh"
                    ;;
                *)
                    profile='your profile'
                    init="-"
                    ;;
            esac

            {   echo "# Load manage by adding the following to ${profile}:"
                echo
                echo "eval \"\$(${MANAGE_DIRECTORY}/bin/manage _manage_shell ${init})\""
                echo
            } >&2

            exit 1
            ;;
        *)
            echo "PATH=\"${MANAGE_DIRECTORY}/libexec:\$PATH\""
    esac
}
